# Generated by Django 5.2.14 on 2026-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('На модерации', 'На модерации'), ('Опубликован', 'Опубликован')], default='На модерации', max_length=30),
        ),
    ]
