# Generated by Django 5.2.14 on 2026-05-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='cities',
            field=models.CharField(blank=True, help_text='Города маршрута через запятую, например: Токио, Киото, Осака', max_length=300),
        ),
    ]
