# Generated by Django 5.2.14 on 2026-05-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tour_cities_jsonfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='city',
        ),
    ]
